### ISSUE TITLE
Can't login to emby

### ISSUE THREAD

**Issue by t-900-a** [dkanada/gelli#115]
Jellyfin and emby have the exact same api, so there should be no api incompatibilities.

Emby version: 4.5.4

Error message when logging into server: "please update your server to the latest version"

Code in-question:
https://github.com/dkanada/gelli/blob/53657919afba1e03265c7e03895822db311443fb/app/src/main/java/com/dkanada/gramophone/activities/LoginActivity.java#L124

Fix:
Revise the version check to support both jellyfin and emby.

**Comment by dkanada** [comment]
We no longer have the same API, and haven't for quite a while now. I don't want to make this change because it would open the floodgates for full Emby support which I don't really want to deal with. The next stable Jellyfin release will be out in the next month and will diverge even further from Emby's API since we migrated the entire web stack to a new library.

**Comment by t-900-a** [comment]
Makes sense,


long live jellyfin
